### ISSUE TITLE
Replitでdiscord-ext-uiがインストールできない

### ISSUE THREAD

**Issue by gx1285JP** [sizumita/discord-ext-ui#15]
Replit: Updating package configuration

--> python3 -m poetry add discord-ext-ui
Using version ^2.1.2 for discord-ext-ui

Updating dependencies
Resolving dependencies...

  SolverProblemError

  The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - discord-ext-ui requires Python >=3.8.2, so it will not be satisfied for Python >=3.8,<3.8.2
  
  Because no versions of discord-ext-ui match >2.1.2,<3.0.0
   and discord-ext-ui (2.1.2) requires Python >=3.8.2, discord-ext-ui is forbidden.
  So, because repl-python3-stetusplay-61 depends on discord-ext-ui (^2.1.2), version solving failed.

  at /opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For discord-ext-ui, a possible solution would be to set the `python` property to ">=3.8.2,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
exit status 1

Replit: Package operation failed.
と出てdiscord-ext-uiがインストールできません

**Comment by sevenc-nanashi** [comment]
replitのPythonのバージョンの問題かと。
ここで言うことではない気がします。
